language: python
sudo: required
services: docker
stages:
- test
- deploy-pypi
- deploy-github

env:
- DOCKER=python:3.5-stretch RUNCOVERAGE=1 ROBOTPY_NO_DEPS=1 
- DOCKER=python:3.6-stretch RUNCOVERAGE=1 ROBOTPY_NO_DEPS=1 
- DOCKER=python:3.7-stretch RUNCOVERAGE=1 ROBOTPY_NO_DEPS=1 

script:
- pwd && ls
- docker run -v$(pwd)/:/src -e "RUNCOVERAGE=$RUNCOVERAGE" -e "ROBOTPY_NO_DEPS=$ROBOTPY_NO_DEPS" -t $DOCKER bash /src/docker_run.sh

jobs:
  include:
  - stage: deploy-pypi
    if: tag IS present
    install: true
    script: cd hal-sim
    deploy:
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      on:
        tags: true
  - stage: deploy-pypi
    if: tag IS present
    install: true
    script: cd hal-base
    deploy:
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      on:
        tags: true
  - stage: deploy-pypi
    if: tag IS present
    install: true
    script: cd hal-roborio
    deploy:
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      on:
        tags: true
  - stage: deploy-pypi
    install: true
    if: tag IS present
    script: cd wpilib
    deploy:
      provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      on:
        tags: true
  - stage: deploy-github
    if: tag IS present
    install: true
    script: devtools/build_installer.sh
    deploy:
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file_glob: true
      file: dist/robotpy-*.zip
      skip_cleanup: true
      on:
        tags: true

git:
  depth: 200
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
