language: python
sudo: false
env:
  - RUNCOVERAGE=1 ROBOTPY_NO_DEPS=1
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -U pip
  - "pushd wpilib; pip install -r travis-requirements.txt; popd"
  - pip install -r docs/requirements.txt
# command to run tests
script:
  - wpilib/tests/run_tests.sh
  - "pushd docs && make html && popd"
git:
  depth: 200
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
